### ISSUE TITLE
Vimeo Integration

### ISSUE THREAD

**Issue by djamg** [hasgeek/funnel#1062]
Request for Vimeo embed support on the platform:

1. Vimeo live player embed for live streaming.
2. Vimeo player for finished streams/pre-recorded videos.

References:
https://developer.vimeo.com/api/oembed/videos#embedding-videos-with-domain-privacy
https://developer.vimeo.com/api/oembed/rles

**Comment by jace** [comment]
Vimeo embed is already supported. The requirement is for exclusive uss. If a project (or profile) claims a video, no other project (or profile) should be able to embed the same video. The logic is:

1. A project offers videos to paid participants.
2. To ensure others cannot view it, the video is marked as embed-only on Vimeo, with the only valid embed domain being hasgeek.com
3. However, anyone can open a new project and embed the same video, bypassing the participant-only limitation of the original project. For this reason, the embed must be exclusive to the first claimant.
4. To be decided: is exclusivity limited to the project or the profile? The profile may want to offer it in multiple projects, but because project content is managed by project editors and not profile admins, this is not the profile admins decision. We don't have a framework for sharing authorisation between projects.

**Comment by jace** [comment]
Anyone can submit a proposal with a video embed, so project-level exclusivity is not good enough. It needs to be a more specific definition, like "project editor content only", which currently is (a) project description and (b) sessions.

However, sessions are likely to become a little more free-form in future as there is a plan for multiple sessions per proposal, treating activities like rehearsals as sessions. Adding video exclusivity will remove this future flexibility from sessions.

**Comment by jace** [comment]
Support for Vimeo videos was added in #1150. @djamg can you confirm if this works for livestreams as well?

**Comment by djamg** [comment]
Supports:
- [x] Public videos
- [x] Videos with embed privacy
- [x] Videos with password protection

**Comment by jace** [comment]
Cool. Close this ticket then? Participant-only videos are a separate problem.
