### ISSUE TITLE
Unscheduled sessions should be possible

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#290]
Sessions represent the event owner's copy of a Proposal, allowing for customisation without changing the original. However, when scheduling events, @zainabbawa frequently finds herself moving proposals into and out of the schedule to find a correct fit. Since sessions require a mandatory start/end time, this means session objects are created and deleted on such moves, losing all customisation.

Instead, sessions should support an unscheduled mode and should not be deleted. This is necessary to preserve customisations and to support featuring (#289) before the schedule is finalised.

**Comment by iambibhas** [comment]
This can be handled like this without much change to UI right now - 
1. the first time a session is created on schedule, create session object and link to proposal,
2. if the session is deleted, delete datetime from session but keep the session object
3. if the session is created again in front end, fetch the last created session for the proposal in the given project schedule, instead of creating a new session object.

**Comment by jace** [comment]
This approach works. Let's do this.
