### ISSUE TITLE
Announce event date without adding a schedule

### ISSUE THREAD

**Issue by qurbat** [hasgeek/funnel#560]
**Scenario:** Organizers may sometimes have a decided date on which they'll host their event or conference, though they may not have a decided (or even a tentative) schedule for the particular day. As of now, if a schedule has not been added, events do not show up on the homepage. This has so far been bypassed by adding placeholder schedules, though that should not be the case.

For flexibility, it should be possible to announce an event date without having to define a schedule for it. As a result of this, events that are in the process of being developed will also become more discoverable.

**Comment by jace** [comment]
We took an explicit decision against allowing this. There are only two modes for a user to participate in a project: as a presenter or as an attendee. For the first, the CfP must be opened. For the second, the schedule must be published. There is nothing for an attendee to do otherwise, and such schedule-free projects will hinder visibility of more advanced projects.
